# Generated by Django 4.0.6 on 2022-07-21 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_user_is_online_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followers_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='followings_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
