# Generated by Django 4.0.6 on 2022-07-21 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_user_followers_number_user_followings_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='follows',
            new_name='follower',
        ),
    ]
