# Generated by Django 4.0.6 on 2022-07-21 10:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_rename_follows_user_follower'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='followers_number',
            new_name='follower_count',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='followings_number',
            new_name='following_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='block_user',
        ),
        migrations.AddField(
            model_name='user',
            name='block_user',
            field=models.ManyToManyField(blank=True, null=True, related_name='block_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
