# Generated by Django 4.0.6 on 2022-07-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='salaryies',
            field=models.CharField(blank=True, choices=[('3 million', '3 milliongacha'), ('3 - 7 ', '3 - 7'), ('7 -15', '7 -15'), ('15 <<<< ', '15 <<<<<')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='time',
            field=models.CharField(blank=True, choices=[('24 soat', '24 soat'), ('3 kun', '3 kun'), ('7 kun', '7 kun'), ('butun vaqt', 'butun vaqt')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(blank=True, choices=[('premium', 'premium'), ('urgant', 'urgant'), ('basic', 'basic')], max_length=20, null=True),
        ),
    ]
