# Generated by Django 4.0.6 on 2022-07-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_salaryies_job_time_alter_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='region',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='salaryies',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
